apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: test-project
  source:
    path: apps
    repoURL: https://github.com/chmikata/argo-main.git
    targetRevision: main
  syncPolicy:
    automated: {}
